<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-0M1LMKLU" failures="1" tests="8" name="com.api.tests.TestAPIScript" time="1.904" errors="0" timestamp="13 Apr 2023 11:03:12 GMT" skipped="3">
  <testcase classname="com.api.tests.TestAPIScript" name="ValidateStatusCodeGetUsersQueryParam" time="0.159"/>
  <testcase classname="com.api.tests.TestAPIScript" name="ValidateStatusCodeGetUsersResponseBody" time="0.141">
    <skipped/>
  </testcase> <!-- ValidateStatusCodeGetUsersResponseBody -->
  <testcase classname="com.api.tests.TestAPIScript" name="ValidateStatusCodePathParams" time="0.201"/>
  <testcase classname="com.api.tests.TestAPIScript" name="ValidateStatusCodeGetUsersResponseBody" time="0.151">
    <skipped/>
  </testcase> <!-- ValidateStatusCodeGetUsersResponseBody -->
  <testcase classname="com.api.tests.TestAPIScript" name="ValidateStatusCodeGetUsersHeaders" time="0.153"/>
  <testcase classname="com.api.tests.TestAPIScript" name="ValidateStatusCodeGetUsersResponseBody" time="0.114">
    <skipped/>
  </testcase> <!-- ValidateStatusCodeGetUsersResponseBody -->
  <testcase classname="com.api.tests.TestAPIScript" name="ValidateStatusCodeGetUsers" time="0.819"/>
  <testcase classname="com.api.tests.TestAPIScript" name="ValidateStatusCodeGetUsersResponseBody" time="0.166">
    <failure message="expected [201] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [201] but found [200]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:652)at org.testng.Assert.assertEquals(Assert.java:662)at com.api.tests.TestAPIScript.ValidateStatusCodeGetUsersResponseBody(TestAPIScript.java:45)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:568)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- ValidateStatusCodeGetUsersResponseBody -->
</testsuite> <!-- com.api.tests.TestAPIScript -->
